function readSavedCart(){try{const value=JSON.parse(localStorage.getItem('andiamo-cart')||'[]');return Array.isArray(value)?value.filter(i=>Number.isFinite(i.price)&&Number.isInteger(i.qty)&&i.qty>0&&i.qty<100):[]}catch{return[]}}
function readSavedMode(){try{return localStorage.getItem('andiamo-mode')==='delivery'?'delivery':'pickup'}catch{return'pickup'}}
const API = 'data/catalog.json';
const categoryOrder=['Pizzas','Menus','Burgers','Burgers Gourmets','Sandwichs','Tacos','TexMex','Pâtes','Salades','Desserts','Glaces','Boissons'];
function imageSlug(name){return name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function productImage(product){return `assets/products/${imageSlug(product.name)}.webp`}
const fallback=[
  {id:'r',name:'Pizza Reine',category:'Pizzas',description:'Sauce tomate, mozzarella, jambon, champignons, olives',image:'assets/pizza-reine.webp',sizes:{Junior:10,Senior:15,Méga:21}},
  {id:'f',name:'Pizza 4 Fromages',category:'Pizzas',description:'Sauce tomate, mozzarella, gorgonzola, chèvre, bleu',image:'assets/pizza-4-fromages.webp',sizes:{Junior:10,Senior:17,Méga:23}},
  {id:'b',name:'Burger Crispy',category:'Burgers Gourmets',description:'Poulet croustillant, cheddar, salade, tomates, sauce',image:'assets/burger-crispy.webp',sizes:{Unique:10.9}},
  {id:'p',name:'Pasta Alfredo',category:'Pâtes',description:'Crème, poulet, champignons et parmesan',image:'assets/pasta-chicken.webp',sizes:{Unique:10.9}}
];
let products=[],filtered=[],visible=12,activeCategory='Tous',cart=readSavedCart(),mode=readSavedMode();
const euro=n=>n.toLocaleString('fr-FR',{style:'currency',currency:'EUR'});
const clean=s=>(s||'').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&#8217;/g,'’').trim();
function normalize(raw){const map=new Map(); raw.forEach(p=>{let category=p.categories?.[0]?.name||'Autres';const pizza=/^Pizzas? /i.test(category);let name=p.name.replace(/ Pizza /i,' Pizza ').replace(/ (Junior|Senior|Méga)$/i,'').trim();if(pizza){category='Pizzas';name=name.replace(/^Pizza\s+/i,'');}const key=(pizza?'pizza-':'item-')+name.toLowerCase();const size=p.name.match(/(Junior|Senior|Méga)$/i)?.[1]||'Unique';const price=Number(p.prices.price)/100;const desc=clean(p.short_description)||'Une recette généreuse préparée à la commande.';if(!map.has(key))map.set(key,{id:key,name:pizza?`Pizza ${name}`:name,category,description:desc,image:p.images?.[0]?.src||'assets/hero-pizza.webp',sizes:{}});map.get(key).sizes[size]=price;});return [...map.values()];}
async function loadCatalog(){try{const raw=await fetch(API).then(r=>{if(!r.ok)throw Error(`Catalogue ${r.status}`);return r.json()});products=normalize(raw);if(!products.length)throw Error('Catalogue vide');}catch{products=[];document.querySelector('.product-grid').innerHTML='<p>La carte est indisponible. Appelez-nous au 01 69 49 59 59.</p>';document.querySelector('.load-more').hidden=true;return}renderCategories();applyFilters();}
function renderCategories(){const available=categoryOrder.filter(c=>products.some(p=>p.category===c));const categories=['Tous',...available];document.querySelector('.category-bar').innerHTML=categories.map(c=>`<button role="tab" aria-selected="${c===activeCategory}" class="${c===activeCategory?'active':''}" data-category="${c}">${c}</button>`).join('');}
function applyFilters(){const q=document.querySelector('#search').value.toLowerCase();filtered=products.filter(p=>(activeCategory==='Tous'||p.category===activeCategory)&&(`${p.name} ${p.description}`.toLowerCase().includes(q)));visible=12;renderProducts();}
function renderProducts(){const shown=filtered.slice(0,visible);const sizeRank={Junior:0,Senior:1,Méga:2,Unique:0};document.querySelector('.product-grid').innerHTML=shown.map(p=>{const entries=Object.entries(p.sizes).sort((a,b)=>sizeRank[a[0]]-sizeRank[b[0]]);const first=entries[0]||['Unique',0];const image=productImage(p);return `<article class="product-card" data-id="${p.id}" data-size="${first[0]}"><img class="product-image" src="${image}" alt="${p.name}" loading="lazy" onerror="this.src='assets/hero-pizza.webp'"><div class="product-body"><span class="product-category">${p.category}</span><h3>${p.name}</h3><p class="product-description">${p.description}</p>${entries.length>1?`<div class="size-options">${entries.map(([s,price],i)=>`<button class="${i===0?'active':''}" data-size="${s}" data-price="${price}">${s}</button>`).join('')}</div>`:''}<div class="product-footer"><span class="product-price">${euro(first[1])}</span><button class="add-button" aria-label="Ajouter ${p.name}">+</button></div></div></article>`}).join('');document.querySelector('#result-count').textContent=`${filtered.length} recette${filtered.length>1?'s':''}`;document.querySelector('.load-more').hidden=visible>=filtered.length;}
function addToCart(card){const p=products.find(x=>x.id===card.dataset.id);const size=card.dataset.size;const price=p.sizes[size];const key=`${p.id}-${size}`;const item=cart.find(x=>x.key===key);if(item)item.qty++;else cart.push({key,id:p.id,name:p.name,size,price,image:productImage(p),category:p.category,qty:1});saveCart();showToast(`${p.name} ajoutée au panier`);}
function saveCart(){localStorage.setItem('andiamo-cart',JSON.stringify(cart));localStorage.setItem('andiamo-mode',mode);renderCart();}
function promoDiscount(){if(mode!=='pickup')return 0;const pizzas=cart.filter(i=>i.category==='Pizzas').flatMap(i=>Array(i.qty).fill(i.price)).sort((a,b)=>a-b);let discount=0;for(let i=0;i<Math.floor(pizzas.length/2);i++)discount+=pizzas[i];return discount;}
function renderCart(){document.querySelectorAll('.cart-count').forEach(e=>e.textContent=cart.reduce((s,i)=>s+i.qty,0));const box=document.querySelector('.cart-items');box.innerHTML=cart.length?cart.map(i=>`<article class="cart-item" data-key="${i.key}"><img src="${i.image}" alt=""><div><h4>${i.name}</h4><small>${i.size==='Unique'?'':i.size+' · '}${euro(i.price)}</small></div><div class="qty"><button data-delta="-1">−</button><b>${i.qty}</b><button data-delta="1">+</button></div></article>`).join(''):'<div class="empty-cart"><b>Votre panier est vide</b><p>Ajoutez une recette qui vous fait envie.</p></div>';const subtotal=cart.reduce((s,i)=>s+i.price*i.qty,0),discount=promoDiscount();document.querySelector('#subtotal').textContent=euro(subtotal);document.querySelector('#discount').textContent=`− ${euro(discount)}`;document.querySelector('#total').textContent=euro(subtotal-discount);document.querySelector('.discount-row').hidden=mode!=='pickup';document.querySelector('.promo-status').hidden=mode!=='pickup';document.querySelector('.checkout-button').disabled=!cart.length;document.querySelectorAll('.order-mode button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));}
function openCart(open=true){document.querySelector('.cart-drawer').classList.toggle('open',open);document.querySelector('.cart-drawer').setAttribute('aria-hidden',String(!open));document.querySelector('.overlay').classList.toggle('open',open);document.body.style.overflow=open?'hidden':'';}
function showToast(msg){const t=document.querySelector('.toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
document.addEventListener('click',e=>{const cat=e.target.closest('[data-category]');if(cat){activeCategory=cat.dataset.category;renderCategories();applyFilters()}const size=e.target.closest('.size-options button');if(size){const card=size.closest('.product-card');card.dataset.size=size.dataset.size;card.querySelectorAll('.size-options button').forEach(b=>b.classList.toggle('active',b===size));card.querySelector('.product-price').textContent=euro(Number(size.dataset.price))}if(e.target.closest('.add-button'))addToCart(e.target.closest('.product-card'));if(e.target.closest('.cart-trigger'))openCart();if(e.target.closest('.cart-close')||e.target.classList.contains('overlay'))openCart(false);const m=e.target.closest('.order-mode button');if(m){mode=m.dataset.mode;saveCart()}const q=e.target.closest('.qty button');if(q){const item=cart.find(i=>i.key===q.closest('.cart-item').dataset.key);item.qty+=Number(q.dataset.delta);cart=cart.filter(i=>i.qty>0);saveCart()}if(e.target.closest('.load-more')){visible+=12;renderProducts()}if(e.target.closest('.checkout-button'))showToast('Module de paiement à connecter avec la pizzeria')});
document.querySelector('#search').addEventListener('input',applyFilters);const menuToggle=document.querySelector('.menu-toggle'),mobileNav=document.querySelector('.site-header nav');function setMenu(open){mobileNav.classList.toggle('mobile-open',open);menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'Fermer le menu':'Ouvrir le menu')}menuToggle.addEventListener('click',()=>setMenu(!mobileNav.classList.contains('mobile-open')));mobileNav.addEventListener('click',e=>{if(e.target.closest('a'))setMenu(false)});document.addEventListener('click',e=>{if(mobileNav.classList.contains('mobile-open')&&!e.target.closest('.site-header'))setMenu(false)});renderCart();loadCatalog();
